// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// announcements.js
export const SET_ANNOUNCEMENTS = 'SET_ANNOUNCEMENTS'
export const SET_ANNOUNCEMENT = 'SET_ANNOUNCEMENT'

// notifications.js
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const SET_UNREAD_NOTIFICATIONS = 'SET_UNREAD_NOTIFICATIONS'

// positions.js
export const FETCH_POSITIONS = 'FETCH_POSITIONS'
export const FETCH_SINGLE_POSITION = 'FETCH_SINGLE_POSITION'
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS'
export const FETCH_POSITION_FAILURE = 'FETCH_POSITION_FAILURE'
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const SAVE_POSITION = 'SAVE_POSITION'

// handbook.js
export const SET_HANDBOOK = 'SET_HANDBOOK'
export const FETCH_ALL_HANDBOOKS = 'FETCH_ALL_HANDBOOKS'
export const FETCH_HANDBOOK = 'FETCH_HANDBOOK'
export const SAVE_HANDBOOK = 'SAVE_HANDBOOK'
export const DELETE_HANDBOOK = 'DELETE_HANDBOOK'

// handbooks-page.js
export const FETCH_ALL_HANDBOOKS_PAGE = 'FETCH_ALL_HANDBOOKS_PAGE'
export const FETCH_HANDBOOK_PAGE = 'FETCH_HANDBOOK_PAGE'
export const SAVE_HANDBOOK_PAGE = 'SAVE_HANDBOOK_PAGE'
export const DELETE_HANDBOOK_PAGE = 'DELETE_HANDBOOK_PAGE'
export const SELECT_HANDBOOK_PAGE = 'SELECT_HANDBOOK_PAGE'

// users.js
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER'
export const SAVE_USER = 'SAVE_USER'
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE'
export const FETCH_STATES = 'FETCH_STATES'
export const FETCH_STATES_FAILURE = 'FETCH_STATES_FAILURE'
export const FETCH_CITIES = 'FETCH_CITIES'
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE'

// attendances.js
export const SET_ATTENDANCES = 'SET_ATTENDANCES'
export const SET_ATTENDANCE = 'SET_ATTENDANCE'
export const SET_ATTENDANCE_TODAY = 'SET_ATTENDANCE_TODAY'

// course-category.js
export const SET_COURSE_CATEGORY = 'SET_COURSE_CATEGORY'
export const FETCH_ALL_COURSE_CATEGORIES = 'FETCH_ALL_COURSE_CATEGORIES'
export const FETCH_COURSE_CATEGORY = 'FETCH_COURSE_CATEGORY'
export const SAVE_COURSE_CATEGORY = 'SAVE_COURSE_CATEGORY'
export const DELETE_COURSE_CATEGORY = 'DELETE_COURSE_CATEGORY'

// course.js
export const SET_COURSE = 'SET_COURSE'
export const FETCH_ALL_COURSES = 'FETCH_ALL_COURSES'
export const FETCH_COURSE = 'FETCH_COURSE'
export const SAVE_COURSE = 'SAVE_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
