// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// announcements.js
export const SET_ANNOUNCEMENTS = 'SET_ANNOUNCEMENTS'
export const SET_ANNOUNCEMENT = 'SET_ANNOUNCEMENT'

// notifications.js
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'

// positions.js
export const FETCH_POSITIONS = 'FETCH_POSITIONS'
export const FETCH_SINGLE_POSITION = 'FETCH_SINGLE_POSITION'
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS'
export const FETCH_POSITION_FAILURE = 'FETCH_POSITION_FAILURE'
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const SAVE_POSITION = 'SAVE_POSITION'

// users.js
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER'
export const SAVE_USER = 'SAVE_USER'
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE'
export const FETCH_STATES = 'FETCH_STATES'
export const FETCH_STATES_FAILURE = 'FETCH_STATES_FAILURE'
export const FETCH_CITIES = 'FETCH_CITIES'
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE'